name: Build and push docker image to ECR

on:
  workflow_dispatch:

jobs:
   build:
      runs-on: ubuntu-latest
     
      steps: 
      - name: checkout code
        uses: actions/checkout@v3

      - name: Configure-AWS-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Log in to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ID }}
        continue-on-error: false

      - name: Build Docker image
        run: |
          docker build -t project_image_yd:ECS_image .

      - name: Tag Docker image
        run: |
          docker tag project_image_yd:ECS_image ${{ secrets.AWS_ID }}/project_image_yd:ECS_image

      - name: Push Docker image to AWS ECR
        run: |
          docker push ${{ secrets.AWS_ID }}/project_image_yd:ECS_image




